owner: jorritb
name: lehtio_input_output
categories:
- Proteomics
description: Lehtio lab io-tools
long_description: |
  Internal tools for input and output of proteomics data, contain
  QC for output of msstitch
  Import of files from storage
  Tar packager for collections
type: unrestricted
